FROM williamyeh/ansible:centos6

# Add your playbooks to the Docker image
ADD . /tmp
WORKDIR /tmp

# Execute Ansible with your playbook's primary entry point.
# The "-c local" argument causes Ansible to use a "local connection" that won't attempt to
# ssh in to localhost.
RUN ansible-playbook fortress-tomcat.yml -c local --sudo

EXPOSE 8080
CMD ["/usr/share/tomcat/bin/catalina.sh", "run"]
