---
# file: fortress.yml

- hosts: fortress
  sudo: yes
  roles:
    - base
    - java
    - maven
    - ldap-tools
    - fortress-source
#    - apacheds
    - openldap
    - fortress
    - tomcat
    - fortress-tomcat
