---
# file: fortress.yml

- hosts: fortress
  sudo: yes
  roles:
    - base
    - java
    - maven
    - ldap-tools
    - { role: fortress-source, ldap_type: openldap }
#    - apacheds
    - openldap
    - fortress
    - tomcat
    - fortress-tomcat
