---
# File: roles/fortress/vars/main.yml

fortress_download_location: "http://iamfortress.org/sites/all/modules/pubdlcnt/pubdlcnt.php?file="
fortress_file_location: "http://iamfortress.org/sites/default/files/"

fortress_file_prefix: "fortressBuilder-Redhat-Silver-i386-"
fortress_file_suffix: ".zip"
fortress_file: "{{ fortress_file_prefix }}{{ fortress_version }}{{ fortress_file_suffix }}"

fortress_file_url: "{{ fortress_file_location }}{{ fortress_file }}"
fortress_download_url: "{{ fortress_download_location }}{{ fortress_file_url }}"

fortress_user: "fortress"
fortress_group: "fortress"
fortress_home: "/opt/fortress"
