---
# file: roles/fortress/tasks/main.yml
#
# This script is based on ten minute guide (http://directory.apache.org/fortress/gen-docs/latest/apidocs/org/apache/directory/fortress/core/doc-files/ten-minute-guide.html)
#

# Section I - Fortress core setup and install

- name: copy build.properties
  command: chdir={{ fortress_core }} cp build.properties.example build.properties

- name: install fortress core with maven
  shell: chdir={{ fortress_core }} /usr/local/maven/bin/mvn clean install

- name: load fortress data (refreshLDAPData.xml)
  command: chdir={{ fortress_core }} /usr/local/maven/bin/mvn install -Dload.file=./ldap/setup/refreshLDAPData.xml

- name: load fortress data (DelegatedAdminManagerLoad.xml)
  command: chdir={{ fortress_core }} /usr/local/maven/bin/mvn install -Dload.file=./ldap/setup/DelegatedAdminManagerLoad.xml

# Section II - Fortress realm install

- name: install fortress realm with maven
  command: chdir={{ fortress_realm }} /usr/local/maven/bin/mvn clean install

- name: move realm jar to tomcat
  shell: chdir={{ fortress_realm }}/proxy/target cp *.jar /usr/share/tomcat/lib

# Section III - Fortress commander install

- name: copy fortress.properties into commander
  command: cp {{ fortress_core }}/config/fortress.properties  {{ fortress_commander }}/src/main/resources

- name: load policies for testing
  command: chdir={{ fortress_commander }} /usr/local/maven/bin/mvn install -Dload.file=./src/main/resources/FortressWebDemoUsers.xml

- name: load tomcat users
  lineinfile: dest=/usr/share/tomcat/conf/tomcat-users.xml state=present
              line="<role rolename=\"manager-script\"/><role rolename=\"manager-gui\"/><user username=\"tcmanager\" password=\"m@nager123\" roles=\"manager-script\"/><user username=\"tcmanagergui\" password=\"m@nager123\" roles=\"manager-gui\"/>"
              insertbefore="</tomcat-users>"

- name: restart tomcat
  service: name=tomcat state=restarted

- name: deploy fortress web to tomcat
  command: chdir={{ fortress_commander }} /usr/local/maven/bin/mvn tomcat:redeploy

# Section IV - Fortress enmasse (REST service) install

- name: copy fortress.properties
  command: cp {{ fortress_core }}/config/fortress.properties {{ fortress_enmasse }}/src/main/resources

- name: turn off doclint to get past javadoc error in java 1.8
  lineinfile: dest={{ fortress_enmasse }}/pom.xml state=present
              line="<additionalparam>-Xdoclint:none</additionalparam>"
              regexp="<!--<additionalparam>-Xdoclint:none<\/additionalparam>-->"

- name: load policies for testing
  command: chdir={{ fortress_enmasse }} /usr/local/maven/bin/mvn install -Dload.file=./src/main/resources/FortressRestServerPolicy.xml

- name: deploy fortress enmasse to tomcat
  command: chdir={{ fortress_enmasse }} /usr/local/maven/bin/mvn tomcat:redeploy


