---
# file: roles/fortress/tasks/main.yml
#
# This script is based on ten minute guide (http://directory.apache.org/fortress/gen-docs/latest/apidocs/org/apache/directory/fortress/core/doc-files/ten-minute-guide.html)
#
 
# Section I - Checkout Fortress source code

- name: create the fortress directory
  file: path=/opt/fortress state=directory

- name: git clone fortress core repo
  git: dest={{ fortress_home }}/directory-fortress-core repo=https://git-wip-us.apache.org/repos/asf/directory-fortress-core.git force=yes version={{ fortress_git_version }}

# fix fortress properties

- name: set server type in build.properties.example
  lineinfile: dest={{ fortress_core }}/build.properties.example state=present
              regexp="ldap\.server\.type" line="ldap.server.type=openldap"
  when: ldap_type == "openldap"

- name: set port in build.properties.example
  lineinfile: dest={{ fortress_core }}/build.properties.example state=present
              regexp="ldap\.port" line="ldap.port=389"
  when: ldap_type == "openldap"

- name: set root user in build.properties.example
  lineinfile: dest={{ fortress_core }}/build.properties.example state=present
              regexp="root\.dn" line="root.dn=cn=Manager,dc=example,dc=com"
  when: ldap_type == "openldap"

- name: set host in build.properties.example
  lineinfile: dest={{ fortress_core }}/build.properties.example state=present
              regexp="ldap\.host" line="ldap.host={{ ldap_host }}"


- name: git clone fortress realm repo
  git: dest={{ fortress_home }}/directory-fortress-realm repo=https://git-wip-us.apache.org/repos/asf/directory-fortress-realm.git force=yes version={{ fortress_git_version }}

- name: git clone fortress commander repo
  git: dest={{ fortress_home }}/directory-fortress-commander repo=https://git-wip-us.apache.org/repos/asf/directory-fortress-commander.git force=yes version={{ fortress_git_version }}

- name: git clone fortress enmasse repo
  git: dest={{ fortress_home }}/directory-fortress-enmasse repo=https://git-wip-us.apache.org/repos/asf/directory-fortress-enmasse.git force=yes version={{ fortress_git_version }}
